# Generated by Django 3.2.8 on 2021-10-06 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
